name: CUPS AirPrint & SANE AirScan
version: "1.0.0"
slug: cups-airprint-sane-airscan
description: Unified print and scan server with CUPS AirPrint and SANE AirScan support
url: https://github.com/CatKinKitKat/homeassistant-addon-cups-airprint-sane-airscan
arch:
  - amd64
  - aarch64
  - armv7
usb: true
init: false
startup: services
homeassistant_api: false
host_network: true
privileged:
  - SYS_ADMIN
devices:
  - /dev/bus/usb
ports:
  631/tcp: 631
  6566/tcp: 6566
ports_description:
  631/tcp: CUPS web interface and IPP printing
  6566/tcp: SANE daemon port for scanning
options:
  log_level: info
  # CUPS options
  share_printers: true
  allow_from:
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "10.0.0.0/8"
  # SANE options
  allowed_networks:
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "10.0.0.0/8"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  share_printers: bool
  allow_from: ["str"]
  allowed_networks: ["str"]
