name: General Issue
description: Have a question or issue? State it clearly.
title: "[General]: "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        ## General Issue
        State your question or point directly.
  - type: textarea
    id: details
    attributes:
      label: Details
      description: "What's the issue or question?"
      placeholder: "Describe your issue or question clearly."
    validations:
      required: true
