name: Smoke Test Add-on

on:
  push:
    branches:
      - master

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        run: docker build -t cups-sane-test ./cups-sane

      - name: Run container
        run: docker run -d --name cups-sane-test -p 631:631 -p 8090:8090 cups-sane-test

      - name: Wait for healthy
        run: |
          for i in {1..90}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' cups-sane-test || echo unknown)
            echo "Health: $status"
            [ "$status" = "healthy" ] && exit 0
            sleep 2
          done
          echo "::error::Container did not become healthy"
          docker logs --tail=200 cups-sane-test || true
          exit 1

      - name: Smoke test endpoints
        run: |
          for port in 631 8090; do
            echo "Checking port $port..."
            if ! nc -z -w5 localhost $port; then
              echo "::error::Port $port not open"
              exit 1
            fi
          done

      - name: Cleanup
        if: always()
        run: docker rm -f cups-sane-test
